## YAML Template.
spring:
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true

